---
apiVersion: v1
kind: Service
metadata:
  name: skills-service-service
spec:
  type: NodePort
  selector:
    service: skills-service
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 60002
      targetPort: 50002
